// userland/attack_demo.zig - the assembled bytes of attack_demo.asm.
//
// Generated by hand: `nasm -f bin attack_demo.asm -o attack_demo.bin`,
// bytes copied in below. If attack_demo.asm changes, re-assemble and
// update this. No id_patch_offset needed here - unlike user_demo.zig,
// this only ever runs as a single instance, so there's nothing to
// distinguish between copies of.
pub const image = [_]u8{
    0xC6, 0x05, 0x00, 0x00, 0xC0, 0x0C, 0x58, 0xB8, 0x00, 0x00,
    0x00, 0x00, 0xBB, 0x21, 0x00, 0x00, 0x00, 0xCD, 0x80, 0xB8,
    0x01, 0x00, 0x00, 0x00, 0xCD, 0x80, 0xEB, 0xEB,
};
