// userland/user_demo.zig - the assembled bytes of user_demo.asm.
//
// Generated by hand: `nasm -f bin user_demo.asm -o user_demo.bin`, bytes
// copied in below. If user_demo.asm ever changes, re-assemble and update
// both `image` and `id_patch_offset` together - the offset is the
// position of the `my_id` byte the loader patches per-process so two
// copies of the same code can be told apart on screen.
pub const image = [_]u8{
    0xE8, 0x00, 0x00, 0x00, 0x00, 0x5E, 0xB8, 0x00, 0x00, 0x00, 0x00, 0x0F,
    0xB6, 0x5E, 0x15, 0xCD, 0x80, 0xB8, 0x01, 0x00, 0x00, 0x00, 0xCD, 0x80,
    0xEB, 0xEC, 0x41,
};

/// Offset of the `my_id` byte within `image` (verified via objdump:
/// `here` label is at offset 5, my_id at offset 26, 26-5=21=0x15, which
/// matches the assembled `movzx ebx, byte [esi+0x15]` instruction).
pub const id_patch_offset: usize = 26;
